/*
    ============================================================
    F0RT1KA YARA Rules
    Data Exfiltration and Encryption Simulation
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1020, T1041, T1486, T1055, T1083
    Generated by F0RT1KA Defense Guidance Builder
    ============================================================
*/

/*
    ============================================================
    YARA Rule: F0RT1KA Azure Reconnaissance Script
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1083, T1018, T1552.001
    Confidence: High
    Description: Detects PowerShell scripts performing Azure Storage
                 Explorer reconnaissance and credential discovery
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule F0RTIKA_AzureReconScript {
    meta:
        description = "Detects PowerShell Azure Storage reconnaissance script from F0RT1KA test"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1083,T1018,T1552.001"
        confidence = "high"

    strings:
        // Function names and patterns
        $func1 = "Discover-AzureStorage" ascii wide nocase
        $func2 = "Test-Administrator" ascii wide nocase
        $func3 = "Set-ExecutionPolicyBypass" ascii wide nocase

        // Azure Storage Explorer paths
        $path1 = "StorageExplorer" ascii wide nocase
        $path2 = "Azure Storage Explorer" ascii wide nocase
        $path3 = "\\.azure\\" ascii wide nocase
        $path4 = "AzureStorageExplorer" ascii wide nocase

        // Azure CLI credential files
        $cred1 = "accessTokens.json" ascii wide nocase
        $cred2 = "azureProfile.json" ascii wide nocase
        $cred3 = "service_principal_entries.json" ascii wide nocase
        $cred4 = "msal_http_cache" ascii wide nocase

        // Azure storage patterns
        $storage1 = "blob.core.windows.net" ascii wide nocase
        $storage2 = "table.core.windows.net" ascii wide nocase
        $storage3 = "queue.core.windows.net" ascii wide nocase
        $storage4 = "file.core.windows.net" ascii wide nocase

        // Environment variable names
        $env1 = "AZURE_STORAGE_CONNECTION_STRING" ascii wide
        $env2 = "AZURE_STORAGE_ACCOUNT" ascii wide
        $env3 = "AZURE_STORAGE_KEY" ascii wide
        $env4 = "AZURE_CLIENT_SECRET" ascii wide

        // Registry paths
        $reg1 = "HKCU:\\Software\\Microsoft\\Azure Storage Explorer" ascii wide
        $reg2 = "HKLM:\\SOFTWARE\\Microsoft\\Azure" ascii wide

        // Output indicators
        $output1 = "azure_storage_info.json" ascii wide nocase
        $output2 = "exfiltration_status.txt" ascii wide nocase
        $output3 = "AZURE_RECON_COMPLETE" ascii wide

    condition:
        (
            // Must have at least one function indicator
            any of ($func*) and
            // Plus Azure path patterns
            2 of ($path*) and
            // Plus credential file or env var indicators
            (any of ($cred*) or any of ($env*))
        ) or
        (
            // Alternative: Storage patterns with registry enumeration
            2 of ($storage*) and any of ($reg*)
        ) or
        (
            // High confidence: specific output file indicators
            any of ($output*) and any of ($path*)
        )
}

/*
    ============================================================
    YARA Rule: F0RT1KA Data Exfiltration Script
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1020, T1041, T1560.001
    Confidence: High
    Description: Detects PowerShell data staging and exfiltration
                 simulation scripts
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule F0RTIKA_DataExfiltrationScript {
    meta:
        description = "Detects PowerShell data exfiltration simulation script from F0RT1KA test"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1020,T1041,T1560.001"
        confidence = "high"

    strings:
        // Function names
        $func1 = "Simulate-DataExfiltration" ascii wide nocase
        $func2 = "Test-Administrator" ascii wide nocase

        // Staging indicators
        $stage1 = "C:\\F0\\staging" ascii wide nocase
        $stage2 = "staged_data.zip" ascii wide nocase
        $stage3 = "$stagingDir" ascii wide nocase
        $stage4 = "Staged file for exfiltration" ascii wide nocase

        // High-value file extensions (exfiltration targets)
        $ext1 = "*.pdf" ascii wide
        $ext2 = "*.docx" ascii wide
        $ext3 = "*.xlsx" ascii wide
        $ext4 = "*.p12" ascii wide
        $ext5 = "*.pfx" ascii wide
        $ext6 = "*.key" ascii wide
        $ext7 = "*.pem" ascii wide
        $ext8 = "*.sql" ascii wide

        // Compression patterns
        $compress1 = "Compress-Archive" ascii wide nocase
        $compress2 = "CompressionLevel" ascii wide nocase

        // Cloud service simulation
        $cloud1 = "Azure Blob" ascii wide
        $cloud2 = "AWS S3" ascii wide
        $cloud3 = "Google Drive" ascii wide
        $cloud4 = "OneDrive" ascii wide
        $cloud5 = "Dropbox" ascii wide

        // Status indicators
        $status1 = "EXFIL_DETECTED" ascii wide
        $status2 = "STAGED_FILES:" ascii wide
        $status3 = "EXFILTRATION_SIMULATION_COMPLETE" ascii wide
        $status4 = "exfiltration_status.txt" ascii wide nocase

        // Target directories
        $target1 = "Documents" ascii wide
        $target2 = "Desktop" ascii wide
        $target3 = "Downloads" ascii wide
        $target4 = "ProgramData" ascii wide

    condition:
        (
            // Must have function name
            any of ($func*) and
            // Plus staging indicators
            2 of ($stage*) and
            // Plus compression or cloud patterns
            (any of ($compress*) or 2 of ($cloud*))
        ) or
        (
            // Alternative: High-value extensions with staging
            3 of ($ext*) and any of ($stage*) and any of ($compress*)
        ) or
        (
            // High confidence: status indicators with targets
            any of ($status*) and 2 of ($target*)
        )
}

/*
    ============================================================
    YARA Rule: F0RT1KA Masqueraded Encryption Binary
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1055, T1036.005, T1486
    Confidence: Critical
    Description: Detects the masqueraded conhost.exe encryption
                 simulation binary
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule F0RTIKA_MasqueradedEncryptor {
    meta:
        description = "Detects F0RT1KA masqueraded conhost.exe encryption binary"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1055,T1036.005,T1486"
        confidence = "critical"

    strings:
        // Command line arguments
        $arg1 = "-simulate" ascii wide
        $arg2 = "-target" ascii wide

        // Status messages
        $status1 = "MASQUERADE_DETECTED" ascii wide
        $status2 = "ENCRYPTION_SIMULATION_COMPLETE" ascii wide
        $status3 = "exfiltration_status.txt" ascii wide

        // Test directory patterns
        $path1 = "c:\\F0\\" ascii wide nocase
        $path2 = "C:\\F0\\test_target" ascii wide nocase
        $path3 = "c:\\F0\\staging" ascii wide nocase

        // Encryption simulation patterns
        $enc1 = ".encrypted" ascii wide
        $enc2 = "DECRYPT_INSTRUCTIONS" ascii wide
        $enc3 = "[SIMULATION ONLY - NOT REAL RANSOMWARE]" ascii wide

        // Test UUID
        $uuid = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284" ascii wide

        // Go runtime indicators
        $go1 = "runtime.main" ascii
        $go2 = "main.main" ascii

        // Windows API for console hiding
        $api1 = "kernel32.dll" ascii wide
        $api2 = "FreeConsole" ascii wide
        $api3 = "AllocConsole" ascii wide

    condition:
        uint16(0) == 0x5A4D and  // PE file
        filesize < 10MB and
        (
            // High confidence: simulation status messages
            any of ($status*) and any of ($path*)
        ) or
        (
            // Alternative: encryption patterns with arguments
            any of ($enc*) and any of ($arg*)
        ) or
        (
            // Critical: Test UUID present
            $uuid
        ) or
        (
            // Go binary with console hiding and F0 paths
            all of ($go*) and any of ($api*) and any of ($path*)
        )
}

/*
    ============================================================
    YARA Rule: F0RT1KA Ransom Note Content
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1486
    Confidence: High
    Description: Detects F0RT1KA simulation ransom note content
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule F0RTIKA_RansomNote {
    meta:
        description = "Detects F0RT1KA simulation ransom note content"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1486"
        confidence = "high"

    strings:
        // Specific F0RT1KA ransom note strings
        $note1 = "[SIMULATION ONLY - NOT REAL RANSOMWARE]" ascii wide nocase
        $note2 = "Your files have been encrypted (simulation)" ascii wide nocase
        $note3 = "This is a security test simulation" ascii wide nocase
        $note4 = "DO NOT PANIC - This is not real malware" ascii wide nocase
        $note5 = "Contact your security team" ascii wide nocase

        // Test identifier
        $uuid = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284" ascii wide

        // Generic ransom note patterns (for broader detection)
        $generic1 = "Your files have been encrypted" ascii wide nocase
        $generic2 = "DECRYPT" ascii wide nocase
        $generic3 = "INSTRUCTIONS" ascii wide nocase
        $generic4 = ".onion" ascii wide nocase
        $generic5 = "Bitcoin" ascii wide nocase

    condition:
        (
            // High confidence: F0RT1KA specific strings
            2 of ($note*) or $uuid
        ) or
        (
            // Medium confidence: Generic ransom note with simulation
            any of ($generic*) and any of ($note*)
        )
}

/*
    ============================================================
    YARA Rule: F0RT1KA Encrypted File Marker
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1486
    Confidence: Medium
    Description: Detects files created by F0RT1KA encryption simulation
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule F0RTIKA_EncryptedFileMarker {
    meta:
        description = "Detects files modified by F0RT1KA encryption simulation"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1486"
        confidence = "medium"

    strings:
        // The simulation reverses bytes, so original content
        // "This is test file content for test" reversed patterns
        $reversed1 = { 74 73 65 74 20 72 6F 66 20 74 6E 65 74 6E 6F 63 }  // "tset rof tnetnoC" partial

        // File markers that might be added
        $marker1 = "F0RT1KA_ENCRYPTED" ascii wide
        $marker2 = "ENCRYPTION_TEST" ascii wide

    condition:
        filesize < 1MB and
        (any of ($reversed*) or any of ($marker*))
}

/*
    ============================================================
    YARA Rule: F0RT1KA Exfiltration Test Binary
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1020, T1041, T1486, T1055, T1083
    Confidence: Critical
    Description: Detects the main F0RT1KA data exfiltration test binary
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule F0RTIKA_ExfiltrationTestBinary {
    meta:
        description = "Detects F0RT1KA data exfiltration and encryption test main binary"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1020,T1041,T1486,T1055,T1083"
        confidence = "critical"

    strings:
        // Test phases
        $phase1 = "Phase 1: Dropping Azure reconnaissance" ascii wide
        $phase2 = "Phase 2: Performing Azure Storage Explorer reconnaissance" ascii wide
        $phase3 = "Phase 3: Simulating data exfiltration" ascii wide
        $phase4 = "Phase 4: Executing masqueraded encryption binary" ascii wide
        $phase5 = "Phase 5: Final assessment" ascii wide

        // File names
        $file1 = "azure_reconnaissance.ps1" ascii wide
        $file2 = "data_exfiltration.ps1" ascii wide
        $file3 = "conhost.exe" ascii wide

        // Status messages
        $msg1 = "Starting Data Exfiltration and Encryption Simulation" ascii wide
        $msg2 = "Azure reconnaissance script was quarantined" ascii wide
        $msg3 = "Masqueraded encryption binary was quarantined" ascii wide
        $msg4 = "Data exfiltration and encryption simulation completed" ascii wide

        // Test UUID
        $uuid = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284" ascii wide

        // Go imports/runtime
        $go1 = "github.com/preludeorg" ascii
        $go2 = "runtime.main" ascii

        // Dropper patterns
        $dropper1 = "c:\\F0" ascii wide nocase
        $dropper2 = "Endpoint.Quarantined" ascii
        $dropper3 = "Endpoint.Stop" ascii

    condition:
        uint16(0) == 0x5A4D and  // PE file
        filesize < 20MB and
        (
            // Critical: Test UUID
            $uuid
        ) or
        (
            // High confidence: Multiple phases
            2 of ($phase*)
        ) or
        (
            // High confidence: Status messages with file names
            any of ($msg*) and 2 of ($file*)
        ) or
        (
            // Go binary with dropper patterns
            any of ($go*) and 2 of ($dropper*)
        )
}

/*
    ============================================================
    YARA Rule: PowerShell Azure Credential Harvesting
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1552.001
    Confidence: High
    Description: Generic detection for PowerShell scripts targeting
                 Azure credentials and configurations
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule PowerShell_AzureCredentialHarvesting {
    meta:
        description = "Detects PowerShell scripts harvesting Azure credentials"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1552.001"
        confidence = "high"

    strings:
        // Azure credential file access
        $az_cred1 = /\$env:USERPROFILE\\.azure/ ascii wide nocase
        $az_cred2 = "accessTokens.json" ascii wide nocase
        $az_cred3 = "azureProfile.json" ascii wide nocase
        $az_cred4 = "service_principal" ascii wide nocase

        // Environment variable access
        $env1 = /GetEnvironmentVariable.*AZURE/ ascii wide nocase
        $env2 = /\[Environment\]::GetEnvironmentVariable.*AZURE/ ascii wide nocase

        // Storage connection patterns
        $conn1 = /AZURE_STORAGE_CONNECTION_STRING/ ascii wide
        $conn2 = /DefaultEndpointsProtocol=https;AccountName=/ ascii wide

        // Get-Content or reading operations
        $read1 = /Get-Content.*\.azure/ ascii wide nocase
        $read2 = /\[IO\.File\]::ReadAllText.*\.azure/ ascii wide nocase

        // Suspicious combinations
        $combo1 = /ConvertFrom-Json.*accessToken/ ascii wide nocase
        $combo2 = /ConvertFrom-Json.*azureProfile/ ascii wide nocase

    condition:
        (
            2 of ($az_cred*) and (any of ($read*) or any of ($env*))
        ) or
        (
            any of ($conn*) and any of ($env*)
        ) or
        (
            any of ($combo*)
        )
}

/*
    ============================================================
    YARA Rule: PowerShell Data Staging for Exfiltration
    Test ID: 4b4bd24c-fff5-4de8-982e-6d0fa5e22284
    MITRE ATT&CK: T1074.001, T1560.001
    Confidence: Medium
    Description: Generic detection for PowerShell scripts staging
                 data for exfiltration
    Author: F0RT1KA Defense Guidance Builder
    Date: 2024-01-15
    ============================================================
*/

rule PowerShell_DataStagingForExfiltration {
    meta:
        description = "Detects PowerShell scripts staging data for exfiltration"
        author = "F0RT1KA"
        date = "2024-01-15"
        test_id = "4b4bd24c-fff5-4de8-982e-6d0fa5e22284"
        mitre_attack = "T1074.001,T1560.001"
        confidence = "medium"

    strings:
        // File enumeration patterns
        $enum1 = /Get-ChildItem.*-Recurse.*\*\.pdf/ ascii wide nocase
        $enum2 = /Get-ChildItem.*-Recurse.*\*\.docx/ ascii wide nocase
        $enum3 = /Get-ChildItem.*-Recurse.*\*\.xlsx/ ascii wide nocase
        $enum4 = /Get-ChildItem.*-Recurse.*\*\.p12/ ascii wide nocase
        $enum5 = /Get-ChildItem.*-Recurse.*\*\.pfx/ ascii wide nocase

        // Copy operations to staging
        $copy1 = /Copy-Item.*staging/ ascii wide nocase
        $copy2 = /Copy-Item.*exfil/ ascii wide nocase
        $copy3 = /Copy-Item.*temp.*zip/ ascii wide nocase

        // Compression
        $zip1 = /Compress-Archive.*-DestinationPath/ ascii wide nocase
        $zip2 = /Compress-Archive.*-CompressionLevel/ ascii wide nocase

        // High-value directories
        $dir1 = "$env:USERPROFILE\\Documents" ascii wide nocase
        $dir2 = "$env:USERPROFILE\\Desktop" ascii wide nocase
        $dir3 = "$env:APPDATA" ascii wide nocase
        $dir4 = "C:\\ProgramData" ascii wide nocase

    condition:
        (
            2 of ($enum*) and any of ($copy*)
        ) or
        (
            any of ($zip*) and 2 of ($dir*)
        ) or
        (
            any of ($copy*) and any of ($zip*)
        )
}
