// es_config.go - Elasticsearch Export Configuration (DEFAULT - ES DISABLED)
//
// This file defines Elasticsearch export configuration constants.
// By default, ES export is DISABLED for backward compatibility.
//
// When building with the --es flag, build_all.sh will generate a new es_config.go
// that overrides these defaults with actual endpoint/credentials.
//
// Usage:
//   ./build_all.sh --org sb              # ES disabled (uses this default file)
//   ./build_all.sh --org sb --es prod    # ES enabled (generates new es_config.go)
//
// DO NOT EDIT THIS FILE MANUALLY - it is managed by build_all.sh

package main

// ES_ENABLED controls whether direct Elasticsearch export is attempted
// Set to true by build_all.sh when --es flag is provided
const ES_ENABLED = false

// ES_ENDPOINT is the Elasticsearch endpoint URL (e.g., https://es.example.com:9200)
// Set by build_all.sh from elasticsearch-registry.json
const ES_ENDPOINT = ""

// ES_INDEX is the base index name (date suffix added automatically)
// e.g., "f0-test-results" becomes "f0-test-results-2025.11.28"
const ES_INDEX = ""

// ES_APIKEY is the Elasticsearch API key for authentication
// Set by build_all.sh from environment variable specified in registry
const ES_APIKEY = ""
