#!/bin/bash
# Multi-Stage Intel-Driven Test Build Script
# UNK_RobotDreams Rust Backdoor Execution Chain - 3 stages
#
# CRITICAL BUILD SEQUENCE:
# 1. Build unsigned stage binaries
# 2. Sign stage binaries (BEFORE embedding)
# 3. Verify signatures
# 4. Compress signed binaries with gzip (reduces orchestrator size ~35%)
# 5. Build main orchestrator (embeds SIGNED+COMPRESSED stages)
# 6. Sign orchestrator
# 7. Cleanup temporary binaries
# 8. Calculate hashes and final cleanup
#
# Usage: ./build_all.sh [--org <org-identifier>] [--es <profile>]
# Output: build/<uuid>/<uuid>.exe

set -e
set -u

# ==============================================================================
# CONFIGURATION
# ==============================================================================

TEST_UUID="414a4c61-019f-48ba-934d-d5e91a29a878"

# Stage definitions: "TECHNIQUE:SOURCE_FILE"
declare -a STAGES=(
    "T1204.002:stage-T1204.002"
    "T1059.001:stage-T1059.001"
    "T1071.001:stage-T1071.001"
)

# ==============================================================================
# DO NOT EDIT BELOW THIS LINE
# ==============================================================================

# Parse command-line arguments
ORG_CERT=""
ES_PROFILE=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --org)
            ORG_CERT="$2"
            shift 2
            ;;
        --es)
            ES_PROFILE="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [--org <org-identifier>] [--es <profile>]"
            echo ""
            echo "Options:"
            echo "  --org <id>    Organization for dual signing (UUID or short name)"
            echo "                Examples: sb, 09b59276-9efb-4d3d-bbdd-4b4663ef0c42"
            echo "  --es <prof>   Elasticsearch profile for direct result export"
            echo "                Examples: prod, lab"
            echo "  -h, --help    Show this help message"
            exit 0
            ;;
        *)
            echo "ERROR: Unknown option: $1"
            exit 1
            ;;
    esac
done

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TEST_DIR="${SCRIPT_DIR}"
BUILD_DIR="${PROJECT_ROOT}/build/${TEST_UUID}"

# Source organization registry helper
if [ -f "${PROJECT_ROOT}/utils/resolve_org.sh" ]; then
    source "${PROJECT_ROOT}/utils/resolve_org.sh"
fi

# Source Elasticsearch registry helper
if [ -f "${PROJECT_ROOT}/utils/resolve_es.sh" ]; then
    source "${PROJECT_ROOT}/utils/resolve_es.sh"
fi

# Determine signing mode and resolve certificates
if [ -z "$ORG_CERT" ]; then
    SIGNING_MODE="single"
    PRIMARY_CERT="${PROJECT_ROOT}/signing-certs/F0RT1KA.pfx"
    PRIMARY_PASSWORD_FILE="${PROJECT_ROOT}/signing-certs/.F0RT1KA.pfx.txt"
else
    SIGNING_MODE="dual"
    if command -v resolve_org_to_cert &> /dev/null; then
        CERT_FILE=$(resolve_org_to_cert "$ORG_CERT")
        if [ $? -ne 0 ] || [ -z "$CERT_FILE" ]; then
            echo -e "${RED}ERROR: Could not resolve organization '$ORG_CERT' to certificate${NC}"
            exit 1
        fi
        ORG_CERT_FILE="${PROJECT_ROOT}/signing-certs/${CERT_FILE}"
        ORG_PASSWORD_FILE="${PROJECT_ROOT}/signing-certs/.${CERT_FILE}.txt"
    else
        echo -e "${YELLOW}WARNING: Registry helper not available, using legacy certificate lookup${NC}"
        ORG_CERT_FILE=$(find "${PROJECT_ROOT}/signing-certs" -name "*.pfx" | grep -i "$ORG_CERT" | head -1)
        if [ -z "$ORG_CERT_FILE" ]; then
            echo -e "${RED}ERROR: Could not find certificate for organization: $ORG_CERT${NC}"
            exit 1
        fi
        ORG_PASSWORD_FILE=$(find "${PROJECT_ROOT}/signing-certs" -name ".*" -type f | grep -i "$ORG_CERT" | head -1)
    fi
    SECONDARY_CERT="${PROJECT_ROOT}/signing-certs/F0RT1KA.pfx"
    SECONDARY_PASSWORD_FILE="${PROJECT_ROOT}/signing-certs/.F0RT1KA.pfx.txt"
fi

# Build configuration
GOOS="${GOOS:-windows}"
GOARCH="${GOARCH:-amd64}"

if [ "$GOOS" = "windows" ]; then
    EXT=".exe"
else
    EXT=""
fi

# ==============================================================================
# Elasticsearch Export Configuration
# ==============================================================================

generate_es_config() {
    local config_file="${TEST_DIR}/es_config.go"

    if [ -z "$ES_PROFILE" ]; then
        cat > "${config_file}" << 'EOF'
// es_config.go - Elasticsearch Export Configuration (DISABLED)
// Generated by build_all.sh - DO NOT EDIT MANUALLY

package main

const ES_ENABLED = false
const ES_ENDPOINT = ""
const ES_INDEX = ""
const ES_APIKEY = ""
EOF
        echo "  ES export: DISABLED (no --es flag)"
    else
        if ! command -v resolve_es_to_endpoint &> /dev/null; then
            echo -e "${RED}ERROR: ES registry helper not available${NC}"
            exit 1
        fi
        local es_endpoint=$(resolve_es_to_endpoint "$ES_PROFILE")
        if [ $? -ne 0 ] || [ -z "$es_endpoint" ]; then
            echo -e "${RED}ERROR: Could not resolve ES profile '$ES_PROFILE'${NC}"
            list_es_profiles
            exit 1
        fi
        local es_index=$(resolve_es_to_index "$ES_PROFILE")
        local es_apikey=$(resolve_es_to_apikey "$ES_PROFILE")
        local es_fullname=$(resolve_es_to_fullname "$ES_PROFILE")

        if [ -z "$es_apikey" ]; then
            local apikey_envvar=$(resolve_es_to_apikey_envvar "$ES_PROFILE")
            echo -e "${RED}ERROR: ES API key not set. Please set: export ${apikey_envvar}='your-api-key'${NC}"
            exit 1
        fi

        cat > "${config_file}" << EOF
// es_config.go - Elasticsearch Export Configuration (ENABLED)
// Generated by build_all.sh - DO NOT EDIT MANUALLY
// Profile: ${ES_PROFILE} (${es_fullname})

package main

const ES_ENABLED = true
const ES_ENDPOINT = "${es_endpoint}"
const ES_INDEX = "${es_index}"
const ES_APIKEY = "${es_apikey}"
EOF
        echo "  ES export: ENABLED (profile: ${ES_PROFILE})"
        echo "  ES endpoint: ${es_endpoint}"
        echo "  ES index: ${es_index}"
    fi
}

# ==============================================================================
# Helper Functions
# ==============================================================================

print_header() {
    echo -e "${BLUE}=================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}=================================================${NC}"
}

print_step() {
    echo -e "${GREEN}[$1] $2${NC}"
}

print_warning() {
    echo -e "${YELLOW}WARNING: $1${NC}"
}

print_error() {
    echo -e "${RED}ERROR: $1${NC}"
}

print_success() {
    echo -e "${GREEN}$1${NC}"
}

validate_environment() {
    print_step "0/8" "Validating environment..."

    if [ ! -d "${TEST_DIR}" ]; then
        print_error "Test directory not found: ${TEST_DIR}"
        exit 1
    fi

    if ! command -v go &> /dev/null; then
        print_error "Go is not installed or not in PATH"
        exit 1
    fi

    if [ "$GOOS" = "windows" ]; then
        if [ ! -f "${PROJECT_ROOT}/utils/codesign" ]; then
            print_error "codesign utility not found: ${PROJECT_ROOT}/utils/codesign"
            exit 1
        fi
        if ! command -v osslsigncode &> /dev/null; then
            print_warning "osslsigncode not installed - signature verification will be skipped"
        fi
    fi

    generate_es_config

    print_success "Environment validation passed"
}

# ==============================================================================
# Build Process
# ==============================================================================

print_header "Multi-Stage Test Build: ${TEST_UUID}"

# Step 0: Validate environment
validate_environment

# Change to test directory
cd "${TEST_DIR}"

# Step 1: Build unsigned stage binaries
print_step "1/8" "Building unsigned stage binaries..."
stage_count=0
for stage_def in "${STAGES[@]}"; do
    IFS=':' read -r technique source_file <<< "$stage_def"
    stage_binary="${TEST_UUID}-${technique}${EXT}"
    source_go="${source_file}.go"

    if [ ! -f "${source_go}" ]; then
        print_error "Source file not found: ${source_go}"
        exit 1
    fi

    echo "  Building ${stage_binary} from ${source_go}..."
    GOOS=${GOOS} GOARCH=${GOARCH} go build -o "${stage_binary}" "${source_go}" test_logger.go test_logger_*.go org_resolver.go es_config.go

    if [ ! -f "${stage_binary}" ]; then
        print_error "Failed to build ${stage_binary}"
        exit 1
    fi

    stage_count=$((stage_count + 1))
done
print_success "Built ${stage_count} unsigned stage binaries"

# Step 2: Sign stage binaries (CRITICAL - before embedding)
if [ "$GOOS" = "windows" ]; then
    if [ "$SIGNING_MODE" = "dual" ]; then
        print_step "2/8" "Dual-signing stage binaries (org + F0RT1KA)..."
        for stage_def in "${STAGES[@]}"; do
            IFS=':' read -r technique _ <<< "$stage_def"
            stage_binary="${TEST_UUID}-${technique}${EXT}"
            echo "  Dual-signing ${stage_binary}..."
            "${PROJECT_ROOT}/utils/codesign" sign-nested "${stage_binary}" "${ORG_CERT_FILE}" "${SECONDARY_CERT}"
            if [ $? -ne 0 ]; then
                print_error "Failed to dual-sign ${stage_binary}"
                exit 1
            fi
        done
        print_success "Dual-signed ${stage_count} stage binaries"
    else
        print_step "2/8" "Signing stage binaries (F0RT1KA)..."
        PRIMARY_PASSWORD=$(cat "${PRIMARY_PASSWORD_FILE}" | tr -d '\n\r')
        for stage_def in "${STAGES[@]}"; do
            IFS=':' read -r technique _ <<< "$stage_def"
            stage_binary="${TEST_UUID}-${technique}${EXT}"
            echo "  Signing ${stage_binary}..."
            "${PROJECT_ROOT}/utils/codesign" --cert "${PRIMARY_CERT}" --password "${PRIMARY_PASSWORD}" sign "${stage_binary}"
            if [ $? -ne 0 ]; then
                print_error "Failed to sign ${stage_binary}"
                exit 1
            fi
        done
        print_success "Signed ${stage_count} stage binaries"
    fi
elif [ "$GOOS" = "darwin" ]; then
    print_step "2/8" "Ad-hoc signing stage binaries (macOS)..."
    if command -v codesign &> /dev/null; then
        for stage_def in "${STAGES[@]}"; do
            IFS=':' read -r technique _ <<< "$stage_def"
            stage_binary="${TEST_UUID}-${technique}${EXT}"
            codesign -s - "${stage_binary}"
            echo "  Ad-hoc signed: ${stage_binary}"
        done
        print_success "Ad-hoc signed ${stage_count} stage binaries"
    else
        print_warning "macOS codesign not available - skipping stage signing"
    fi
else
    print_step "2/8" "Signing stage binaries..."
    print_warning "Signing skipped for ${GOOS} (no Authenticode for ELF binaries)"
fi

# Step 3: Verify signatures
print_step "3/8" "Verifying stage signatures..."
if [ "$GOOS" = "windows" ] && command -v osslsigncode &> /dev/null; then
    for stage_def in "${STAGES[@]}"; do
        IFS=':' read -r technique _ <<< "$stage_def"
        stage_binary="${TEST_UUID}-${technique}${EXT}"
        echo "  Verifying ${stage_binary}..."
        if osslsigncode verify "${stage_binary}" 2>&1 | grep -q "Message digest"; then
            echo "    Signature present and valid (self-signed cert)"
        else
            print_error "Could not verify signature for ${stage_binary}"
            exit 1
        fi
    done
    print_success "All stage signatures verified"
elif [ "$GOOS" = "darwin" ]; then
    for stage_def in "${STAGES[@]}"; do
        IFS=':' read -r technique _ <<< "$stage_def"
        stage_binary="${TEST_UUID}-${technique}${EXT}"
        if command -v codesign &> /dev/null && codesign -v "${stage_binary}" 2>/dev/null; then
            echo "  Verified: ${stage_binary}"
        fi
    done
    print_success "Stage signature verification complete"
else
    print_warning "Skipping signature verification (not applicable for ${GOOS})"
fi

# Step 4: Compress signed binaries with gzip
print_step "4/8" "Compressing signed binaries with gzip..."
for stage_def in "${STAGES[@]}"; do
    IFS=':' read -r technique _ <<< "$stage_def"
    stage_binary="${TEST_UUID}-${technique}${EXT}"
    if [ -f "${stage_binary}" ]; then
        orig_size=$(stat -c%s "$stage_binary" 2>/dev/null || stat -f%z "$stage_binary" 2>/dev/null)
        gzip -9 -k "$stage_binary"
        gz_size=$(stat -c%s "${stage_binary}.gz" 2>/dev/null || stat -f%z "${stage_binary}.gz" 2>/dev/null)
        echo "  ${stage_binary}: $(numfmt --to=iec ${orig_size} 2>/dev/null || echo ${orig_size}B) -> $(numfmt --to=iec ${gz_size} 2>/dev/null || echo ${gz_size}B)"
    fi
done
print_success "Compression complete"

# Step 5: Build main orchestrator (embeds SIGNED+COMPRESSED stage binaries)
print_step "5/8" "Building main orchestrator (embedding compressed stages)..."

mkdir -p "${BUILD_DIR}"

main_binary="${BUILD_DIR}/${TEST_UUID}${EXT}"
echo "  Building ${TEST_UUID}${EXT} with embedded stage binaries..."
GOOS=${GOOS} GOARCH=${GOARCH} go build -o "${main_binary}" "${TEST_UUID}.go" test_logger.go test_logger_*.go org_resolver.go es_config.go

if [ ! -f "${main_binary}" ]; then
    print_error "Failed to build main binary: ${TEST_UUID}${EXT}"
    exit 1
fi

main_size_before=$(ls -lh "${main_binary}" | awk '{print $5}')
print_success "Main orchestrator built (${main_size_before})"

# Step 6: Sign main binary
cd "${PROJECT_ROOT}"

if [ "$GOOS" = "windows" ]; then
    if [ "$SIGNING_MODE" = "dual" ]; then
        print_step "6/8" "Dual-signing main binary (org + F0RT1KA)..."
        "${PROJECT_ROOT}/utils/codesign" sign-nested "${main_binary}" "${ORG_CERT_FILE}" "${SECONDARY_CERT}"
        if [ $? -ne 0 ]; then
            print_error "Failed to dual-sign main binary"
            exit 1
        fi
    else
        print_step "6/8" "Signing main binary (F0RT1KA)..."
        "${PROJECT_ROOT}/utils/codesign" --cert "${PRIMARY_CERT}" --password "${PRIMARY_PASSWORD}" sign "${main_binary}"
        if [ $? -ne 0 ]; then
            print_error "Failed to sign main binary"
            exit 1
        fi
    fi

    if command -v osslsigncode &> /dev/null; then
        osslsigncode verify "${main_binary}" > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            print_error "Main binary signature verification failed"
            exit 1
        fi
    fi
elif [ "$GOOS" = "darwin" ]; then
    print_step "6/8" "Ad-hoc signing main binary (macOS)..."
    if command -v codesign &> /dev/null; then
        codesign -s - "${main_binary}"
        print_success "Main binary ad-hoc signed"
    else
        print_warning "macOS codesign not available - skipping"
    fi
else
    print_step "6/8" "Signing main binary..."
    print_warning "Signing skipped for ${GOOS}"
fi

main_size_after=$(ls -lh "${main_binary}" | awk '{print $5}')
print_success "Main binary ready (${main_size_after})"

# Step 7: Cleanup temporary stage binaries
print_step "7/8" "Cleaning up temporary stage binaries..."
cd "${TEST_DIR}"
for stage_def in "${STAGES[@]}"; do
    IFS=':' read -r technique _ <<< "$stage_def"
    stage_binary="${TEST_UUID}-${technique}${EXT}"
    if [ -f "${stage_binary}" ]; then
        echo "  Removing ${stage_binary}..."
        rm -f "${stage_binary}"
    fi
    if [ -f "${stage_binary}.gz" ]; then
        echo "  Removing ${stage_binary}.gz..."
        rm -f "${stage_binary}.gz"
    fi
done
print_success "Stage binaries cleaned up"

# Step 8: Calculate SHA1 hashes and cleanup generated config
print_step "8/8" "Calculating hashes and final cleanup..."

if command -v sha1sum &> /dev/null; then
    main_hash=$(sha1sum "${main_binary}" | awk '{print $1}')
else
    main_hash=$(shasum -a 1 "${main_binary}" | awk '{print $1}')
fi
echo "  SHA1: ${main_hash}"

if [ -f "${TEST_DIR}/es_config.go" ]; then
    echo "  Removing generated es_config.go..."
    rm -f "${TEST_DIR}/es_config.go"
fi

print_success "Final cleanup complete"

# ==============================================================================
# Build Summary
# ==============================================================================

print_header "Build Complete"
echo ""
echo "  Test UUID:        ${TEST_UUID}"
echo "  Stages Built:     ${stage_count}"
echo "  Platform:         ${GOOS}/${GOARCH}"
echo "  Final Binary:     ${main_binary}"
echo "  Binary Size:      ${main_size_after}"
echo "  SHA1 Hash:        ${main_hash}"
if [ -n "$ES_PROFILE" ]; then
echo "  ES Export:        ENABLED (profile: ${ES_PROFILE})"
else
echo "  ES Export:        DISABLED"
fi
echo ""
echo "Stage Techniques:"
for stage_def in "${STAGES[@]}"; do
    IFS=':' read -r technique source_file <<< "$stage_def"
    echo "  - ${technique} (${source_file}.go)"
done
echo ""
print_success "Multi-stage test ready for deployment!"
echo ""
echo "Deployment:"
if [ "$GOOS" = "windows" ]; then
    echo "  1. Copy ${main_binary} to target Windows system"
    echo "  2. Run: C:\\${TEST_UUID}.exe"
elif [ "$GOOS" = "darwin" ]; then
    echo "  1. Copy ${main_binary} to target macOS system"
    echo "  2. Remove quarantine: xattr -cr ${TEST_UUID}"
    echo "  3. Run: /tmp/F0/${TEST_UUID}"
else
    echo "  1. Copy ${main_binary} to target Linux system"
    echo "  2. Run: /tmp/F0/${TEST_UUID}"
fi
echo "  Test will extract and execute stages in killchain order"
if [ -n "$ES_PROFILE" ]; then
echo "  Results will be exported directly to Elasticsearch"
fi
echo ""
