//go:build windows
// +build windows

// es_config.go - Elasticsearch Export Configuration (Build-Time Generated)
//
// This file is auto-generated by build_all.sh when using the --es flag.
// DO NOT commit this file to the repository - it contains build-time configuration.
//
// When building with ES export enabled:
//   ./build_all.sh --org sb --es prod
//
// When building without ES export (default):
//   ./build_all.sh --org sb
//
// The actual ES configuration comes from signing-certs/elasticsearch-registry.json

package main

// ES_ENABLED controls whether direct Elasticsearch export is attempted
// When false, test results are only saved locally (collector handles export)
const ES_ENABLED = false

// ES_ENDPOINT is the Elasticsearch endpoint URL (e.g., https://es.example.com:9200)
// Only used when ES_ENABLED = true
const ES_ENDPOINT = ""

// ES_INDEX is the base index name (date suffix added automatically)
// Example: "f0-test-results" becomes "f0-test-results-2025.12.01"
const ES_INDEX = ""

// ES_APIKEY is the Elasticsearch API key for authentication
// Format: base64 encoded "id:api_key"
const ES_APIKEY = ""
