// es_config.go - Elasticsearch Export Configuration (DEFAULT - ES DISABLED)
//
// This file defines Elasticsearch export configuration constants.
// By default, ES export is DISABLED for backward compatibility.
//
// When building with the --es flag, build_all.sh will generate a new es_config.go
// that overrides these defaults with actual endpoint/credentials.
//
// DO NOT EDIT THIS FILE MANUALLY - it is managed by build_all.sh

//go:build windows
// +build windows

package main

// ES_ENABLED controls whether direct Elasticsearch export is attempted
const ES_ENABLED = false

// ES_ENDPOINT is the Elasticsearch endpoint URL
const ES_ENDPOINT = ""

// ES_INDEX is the base index name (date suffix added automatically)
const ES_INDEX = ""

// ES_APIKEY is the Elasticsearch API key for authentication
const ES_APIKEY = ""
